# -*- coding: utf-8 -*-
"""Diccionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCFW66CSnxaGxcLH6_vJ-qvlKOHodVFa

**Creando un diccionario**
"""

#Almacenar mis notas
notas={"algoritmos":14, "base de datos":16,"matematicas":15}
#Identificar Alumnos
alumnos={"201":"Juan Pérez","202":"María Jaramillo","210":"Claudia Cisneros","300":"Pedro Olaya"}
#Almacenar precios de productos
productos={"Arroz":3.5, "Azucar":3.20, "Aceite":7.8,"Atún":5.4,"Frejol":3.5}
print(notas)
print(alumnos)
print(productos)

print("La nota de Algoritmos es", notas['algoritmos'])
print("El alumno de código 210 es ", alumnos['210'])

for clave in productos:
  print("El producto ",clave, " cuesta ",productos[clave])

"""**Funcion dict**"""

ciudades=dict(LaLibertad="Trujillo",Lambayeque="Chiclayo",Piura="Piura",Tumbes="Tumbes")
print(ciudades)

"""**Funcion zip**"""

frutas=["manzana","pera","piña"] # iterable: cadena, lista o tupla
precios=[2.3,4.5,3.7]
print(dict(zip(frutas,precios)))


numeros="12345" 
nombres=["Uno","Dos","Tres","Cuatro","Cinco"]
print(dict(zip(numeros,nombres)))
print(dict(zip(nombres,numeros)))

"""**Funcion items**"""

diccionario={"mamá":"mother","papá":"father","hijo":"son"}
elementos=diccionario.items();
print(elementos)

"""**Funcion keys / values**"""

verduras={1:"Fresa",2:"Manzana",3:"Plátano",4:"Naranja"}
claves=verduras.keys()
valores= verduras.values()
print(claves)
print(valores)


#####Ejercicios Resueltos#####

"""**Ejercicio 1 **"""

monedas={"Euro":"€","Dolar":"$","Yen":"¥"}
moneda=input("Ingrésame el nombre de una moneda: ")
contador=False
for m in monedas.keys():
  if m==moneda:
    contador=True
if contador==True:
  print(monedas[moneda])
else:
  print("No se encontró moneda")

"""**Ejercicio 2**"""

datos={}
nombre=input("Nombre: ")
edad=int(input("Edad: "))
direccion=input("Direccion: ")
telefono=input("Teléfono" )
datos.setdefault("nombre ",nombre)
datos.setdefault("edad ",edad)
datos.setdefault("direccion ",direccion)
datos.setdefault("telefono",telefono)
print(datos)

"""**Ejercicio 7**"""

cesta={}
agregar="Si"
while agregar=="Si":
  articulo=input("Ingrésame un artículo")
  precio= float(input("Ingrésame un precio"))
  cesta.setdefault(articulo,precio)
  agregar=input("Deseas agregar más")
print(cesta)
suma=0
for v in cesta.values():
  suma=suma+v

print("la suma es: ", suma)

"""**Ejercicio 8**"""

diccionario = {}
palabras = input("Introduce la lista de palabras y traducciones en formato palabra:traducción separadas por comas: ")
for p in palabras.split(','):
    clave, valor = p.split(':')
    diccionario[clave] = valor
frase = input('Introduce una frase en español: ')
for p in frase.split():
    if p in diccionario:
        print(diccionario[p], end=' ')
    else:
        print(p, end=' ')