# -*- coding: utf-8 -*-
"""Excepciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KNpg52OHyADjh06efenjM_S9IsvwWH4q
"""

Errores de Sintaxis

print("Algoritmos)

def Saludar():  
  print("Hola, Python")

"""Excepciones"""

try:
  print(4+5)
except TypeError:
  a=5
  b=6
  print("Sólo se pueden sumar dos numeros")
  print(a+b)

"""Ejercicio 1"""

try:
  n1= int(input("Ingresa primer número "))
  n2 = int(input("Ingresa segundo numero "))
  division=n1/n2
  print("La división es ",division)
except ValueError:
  print("Debes ingresar numeros")
except ZeroDivisionError:
  print("No se puede dividir entre 0")

lista=["Cero","Uno","Dos","Tres"] #0,1,2,3
indice=int(input("Ingresa un indice "))
try:
  print("El valor del indice ingresado es",lista[indice])
except IndexError:
  print("El indice de la lista no existe. Ingrese un indice entre -4 y 3")

"""Ejercicio 3"""

diccionario={"Peru":"Lima","Argentina":"La Paz","Chile":"Santiago"}
ciudad=input("Ingresa un país: ")
try:
  print("La capital es",diccionario[ciudad])
except KeyError:
  print("La clave accedida no existe. Ingrese Peru, Argentina o Chile")

"""Ejercicio 5"""

elementos=[1,2,3]
def agregar_una_vez(lista,el):
  try:
    if el in lista:
      raise ValueError
    else:
      lista.append(el)
  except ValueError:
    print("No se puede agregar repetidos")

agregar_una_vez(elementos,3)