# -*- coding: utf-8 -*-
"""Reforzamiento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ueA-t40nSdQ3pB2H16Swp3r5mSWFhF44

**Ejercicio 1**
"""

frase= input("Ingresa una frase: ")
palabras=frase.split(" ") #Algoritmos y Estructuras de Datos
print("La frase tiene ",len(palabras))

"""**Ejercicio 2**"""

lista1=[3,7,10,12,17]
lista2=[1,8,9,14,16]
lista1.extend(lista2) # lista1 ya creció ahora 10 elementos
lista1.sort()
print(lista1)

"""**Ejercicio 3**"""

def max(a,b):
  mayor=0
  if a>b:
    mayor=a
  else:
    mayor=b
  return mayor

print(max(100,500))

"""**Ejercicio 4**"""

def max_de_tres(a,b,c):
  mayor=0
  if a>=b and a>=c:
    mayor=a
  elif b>=a and b>=c:
    mayor=b
  else:
    mayor=c
  return mayor
print("El mayor es: ",max_de_tres(150,20,1000))

"""**Ejercicio 5**"""

def esVocal(c):
  if c.lower()=="a" or c.lower()=="e" or c.lower()=="i" or c.lower()=="o" or c.lower()=="u":
    return True
  else:
    return False
print("La letra es vocal: ",esVocal("e"))

"""**Ejercicio 6**"""

numero=int(input("Ingresa el numero de latas: ")) # 12
# 1 2 3 4 5 6 7 8 9 10 # 55
s = 0
for i in range (0, int(numero/2)+1):
  s=s+i # 0+1
  if s >numero:
    break;
if (s-i)== numero:
  print("Se puede apilar")
else:
  print("No se puede apilar")

print("La ultima fila de latas apiladas es ", i-1)
print("El total de latas apiladas max es", s-i)

"""**Ejercicio 7**"""

def Multiplicacion(a,b): # 4,10
  print(a,"*",b,"=",end="")
  for i in range(0,a):
    if(i!=a-1):
      print(b,"+",end="")
    else:
      print(b,end="")
  print("=", a*b)

Multiplicacion(4,10)

"""**Ejercicio 9**"""

notas=[]
insuficientes=[]
aprobados=[]
notables=[]
excelentes=[]
cantidad= int(input("¿Cuántas notas ingresará? "))
contador=0
# Ingresar la cantidad de notas que el usuario pidio
while (contador<cantidad):
  nota= int(input("Ingresa nota "+str(contador+1)+" (Entre 0 y 10) "))
  notas.append(nota)
  contador+=1

#verificando cuantas notas son de cada grupo
for n in notas:
  if n<5:
    insuficientes.append(n)
  elif n<7:
    aprobados.append(n)
  elif n<9:
    notables.append(n)
  else:
    excelentes.append(n)

#imprimiendo los resultados
print("La lista de notas: ", notas)
print("Notas Insuficientes: ", len(insuficientes)," - ", insuficientes)
print("Notas Aprobadas: ", len(aprobados)," - ", aprobados)
print("Notas Notables: ", len(notables)," - ", notables)
print("Notas excelentes: ",len(excelentes)," - ",  excelentes)

"""**Ejercicio 12**"""

cifras=[0,1,2,3,4,5,6,7,8,9]
palabras=["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve"]
numero=input("Ingresa un numero: ")
for n in numero:
  for i in range(0,len(cifras)):
    if n==str(cifras[i]):
      print(palabras[i], end=" ")
      break