# -*- coding: utf-8 -*-
"""Taller I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6MljuqyI7NCCDMaaP4GAqDl-6XRSjVM

Ejercicio 10: Programa que lea un carácter por
teclado y compruebe si es una letra
mayúscula.
"""

#Hacerlo con todas las letras
letra=input("Ingresa una letra")
if (letra=="A" or letra=="B" or letra=="C"):
  print("La letra ingresa está en mayúsculas")
else:
  print("La letra ingresa está en minúsculas")

"""Ejercicio 9: Escribir un programa que lea un año
indicar si es bisiesto. Nota: un año es
bisiesto si es un número divisible por 4,
pero no si es divisible por 100, excepto
que también sea divisible por 400.
"""

anio=int(input("Ingresame un año: "))
if ((anio % 4==0 and anio % 100!=0) or anio %400 ==0):
  print("Si es año bisiesto")
else:
  print("No es bisiesto")

"""Ejercicio 8: Programa que lea 3 datos de entrada A, B y C. Estos corresponden a las
dimensiones de los lados de un
triángulo. El programa debe determinar
qué tipo de triangulo es, teniendo en
cuenta los siguiente:
a. Si se cumple Pitágoras entonces
es triángulo rectángulo
b. Si sólo dos lados del triángulo
son iguales entonces es
isósceles.
c. Si los 3 lados son iguales
entonces es equilátero.
d. Si no se cumple ninguna de las
condiciones anteriores, es
escaleno
"""

A=int(input("Ingresa primer lado: "))
B=int(input("Ingresa segundo lado: "))
C=int(input("Ingresa tercer lado: "))
#mayor=0
#menor1=0
#menor=2=0
#Determino el mayor
#if (A>=B and A>=C):
#  mayor=A
#  menor1=B
#  menor2=C
#elif (B>=A and B>=C):
#  mayor=B
#  menor1=A
#  menor2=C
#else:
#  mayor=C
#  menor1=A
#  menor2=B
if(pow(A,2)==pow(B,2)+pow(C,2) or pow(B,2)==pow(A,2)+pow(C,2) or pow(C,2)==pow(B,2)+pow(A,2)):
#if (pow(mayor,2)==pow(menor1,2)+pow(menor2,2)):
  print("Triángulo rectángulo")
elif (A==B and A==C and B==C):
  print("Triángulo equilatero")
elif (A==B or A==C or B==C):
  print("Triángulo isósceles")
else:
  print("Triángulo escaleno")

"""Ejercicio 7: Realiza un programa en Python que
pida por teclado el resultado (dato
entero) obtenido al lanzar un dado de
seis caras y muestre por pantalla el
número en letras (dato cadena) de la
cara opuesta al resultado obtenido.

* a. Nota 1: En las caras opuestas de
un dado de seis caras están los
números: 1-6, 2-5 y 3-4.
* b. Nota 2: Si el número del dado
introducido es menor que 1 o
mayor que 6, se mostrará el
mensaje: “ERROR: número
incorrecto.”.
* c. Ejemplo: Introduzca número
del dado: 5 En la cara opuesta
está el “dos”
"""

numero=int(input("Ingresa el numero del dado: "))
if numero==1:
  print("SEIS")
elif numero==2:
  print("CINCO")
elif numero==3:
  print("CUATRO")
elif numero==4:
  print("TRES")
elif numero==5:
  print("DOS")
elif numero==6:
  print("UNO")
else:
  print("ERROR: número incorrecto.")

"""Ejercicio 20 : Escribe un programa que diga si un
número introducido por teclado es o no
primo. Un número primo es aquel que
sólo es divisible entre él mismo y la
unidad.
"""

numero=int(input("Ingresa un número: ")) #10
#10 ->1, 2 ......10 --> 2
#10 -> 2........9 ->0
cont=0
for i in range(2,numero):
  if(numero%i==0):
    cont+=1 # cont=cont+1
if (cont==0):
  print("Es primo")
else:
  print("No es primo")

"""Ejercicio 19: Escribe un programa que, dados dos
números, uno real (base) y un entero
positivo (exponente), saque por
pantalla el resultado de la potencia. No
se puede utilizar el operador de
potencia (**).
"""

base=int(input("Ingresa la base: "))
exponente=int(input("Ingresa el exponente: "))
#4-->3
potencia=1 #El 1 es el elemento neutro de la multiplicación
for i in range(0,exponente):# for de exponente vueltas: 0,1,2... exponente-1
  potencia= potencia*base #1vuelta= 1*4=4  4*4=16  16*4=64
print("La potencia es ", potencia)

"""Ejercicio 18: . Escribe un programa que lea una lista
de diez números y determine cuántos
son positivos, y cuántos son negativos
"""

contp=0
contn=0
i=0
while i<10:
  numero=int(input("Ingresame un numero"))
  if (numero>=0):
    contp+=1
  else:
    contn+=1
  i+=1
print("Cantidad de + :",contp)
print("Cantidad de - :",contn)

"""Ejercicio 16: . Escribir un programa que imprima
todos los números pares entre dos
números que se le pidan al usuario.
"""

inicio=int(input("Ingresa numero de inicio:"))
fin=int(input("Ingresa numero de fin: "))

nuevo_inicio=0
if inicio%2==0:
  nuevo_inicio=inicio
else:
  nuevo_inicio=inicio+1

nuevo_fin=0  #50
if fin%2==0:
  nuevo_fin=fin+1
else:
  nuevo_fin=fin

for i in range(nuevo_inicio,nuevo_fin):
  print(i)