# -*- coding: utf-8 -*-
"""Taller_II y III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KCTTpRuwNchBe_Yqb_z16LBv-vVhvV7d

Ejercicio 5: Escribir un programa que implemente una agenda. En la agenda se podrán guardar nombres y números de teléfono. El programa nos dará el siguiente menú: a. Añadir/modificar: Nos pide un nombre. Si el nombre se encuentra en la agenda, debe mostrar el teléfono y, opcionalmente, permitir modificarlo si no es correcto. Si el nombre no se encuentra, debe permitir ingresar el teléfono correspondiente. b. Buscar: Nos pide una cadena de caracteres, y nos muestras todos los contactos cuyos nombres comiencen por dicha cadena. c. Borrar: Nos pide un nombre y si existe nos preguntará si queremos borrarlo de la agenda. d. Listar: Nos muestra todos los contactos de la agenda. Implementar el programa con un diccionario.
"""

agenda={}
agenda.setdefault("Pedro","9999999")
print(agenda)
opcion=1
while opcion!=5:
  opcion=int(input("Qué quieres hacer (1=añadir/modificar, 2=buscar,3=borrar, 4=listar, 5=salir)"))
  if opcion==1: # añadir/modificar
    nombre=input("Ingresa un nombre")
    telefono=agenda.get(nombre)
    if telefono==None:
      telefono=input("Ingresame tu telefono")
      agenda.setdefault(nombre,telefono)
    else:
      print("El telefono es",telefono)
      modificar=input("Deseas actualizar el telefono? (S=SI,N=NO)")
      if modificar=="S":
        telefono=input("Ingresa nuevo teléfono")
        agenda[nombre]=telefono
  elif opcion==2:
    print("Buscar")
  elif opcion==3:
    print("Borrar")
  elif opcion==4:
    print(agenda)